name: hogwarts_rules
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_color: any

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #FONDOS
    - images/LOGOS/Logo3.png
    - images/fondoAzul.png

    #GRYFFINDOR
    - images/Gryffindor/gryffindor.png
    - images/Gryffindor/gryffindor2.png
    - images/Gryffindor/Gry1.png
    - images/Gryffindor/Gry2.png
    - images/Gryffindor/Gry3.png
    - images/Gryffindor/LogoGry.png

    #SLYTHERIN
    - images/Slytherin/slytherin.png
    - images/Slytherin/slytherin2.png
    - images/Slytherin/Sly1.png
    - images/Slytherin/Sly2.png
    - images/Slytherin/Sly3.png
    - images/Slytherin/LogoSly.png

    #RAVENCLAW
    - images/Ravenclaw/ravenclaw.png
    - images/Ravenclaw/ravenclaw2.png
    - images/Ravenclaw/Rav1.png
    - images/Ravenclaw/Rav2.png
    - images/Ravenclaw/Rav3.png
    - images/Ravenclaw/LogoRav.png
    
    #HUFFLEPUFF
    - images/Hufflepuff/hufflepuff.png
    - images/Hufflepuff/hufflepuff.png
    - images/Hufflepuff/Huf1.png
    - images/Hufflepuff/Huf2.png
    - images/Hufflepuff/Huf3.png
    - images/Hufflepuff/LogoHuf.png

    #FONDO/IMAGENES LOGIN - PORTADA - REGISTRO
    - images/fondo_01.jpg
    - images/fondo_02.jpg
    - images/fondo_03.jpg
    - images/hat.png
    - images/carta.png
    - images/arrowdown.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BluuNext
      fonts:
        - asset: fonts/BluuNext-Bold.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
