name: hogwarts_rules
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_color: any
  http: "^0.11.3+16"
  form_field_validator: ^1.0.1
  carousel_slider: ^3.0.0
  flip_card: ^0.4.4
  smooth_page_indicator: any
  audioplayers: ^0.15.1
  animated_text_kit: ^3.1.2
  flutter_icons: ^1.1.0
  url_launcher: ^5.0.0
  flutter_rating_bar: ^3.0.0
  dart_random_choice: ^0.0.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #FONDOS
    - images/LOGOS/Logo1.png
    - images/LOGOS/Logo2.png
    - images/LOGOS/Logo3.png
    - images/LOGOS/LogoPeque.png
    - images/fondoMorado.png
    - images/fondoNegro.png
    - images/fondoNegro2.png
    - images/fondoNegro3.png
    - images/Slytherin/slytherin.jpg
    - images/Nosotros/mik.png
    - images/Nosotros/mel.png

    #AVATARES
    - images/Avatares/Avatar1.png
    - images/Avatares/Avatar2.png
    - images/Avatares/Avatar3.png
    - images/Avatares/Avatar4.png
    - images/Avatares/Avatar5.png
    - images/Avatares/Avatar6.png
    - images/Avatares/Avatar7.png

    #GRYFFINDOR
    - images/Gryffindor/gryffindor.png
    - images/Gryffindor/gryffindor.jpg
    - images/Gryffindor/gryffindor2.png
    - images/Gryffindor/Gry1.png
    - images/Gryffindor/Gry2.png
    - images/Gryffindor/Gry3.png
    - images/Gryffindor/LogoGry.png

    #SLYTHERIN
    - images/Slytherin/slytherin.png
    - images/Slytherin/slytherin.jpg
    - images/Slytherin/slytherin2.png
    - images/Slytherin/Sly1.png
    - images/Slytherin/Sly2.png
    - images/Slytherin/Sly3.png
    - images/Slytherin/LogoSly.png

    #RAVENCLAW
    - images/Ravenclaw/ravenclaw.jpg
    - images/Ravenclaw/ravenclaw.png
    - images/Ravenclaw/ravenclaw2.png
    - images/Ravenclaw/Rav1.png
    - images/Ravenclaw/Rav2.png
    - images/Ravenclaw/Rav3.png
    - images/Ravenclaw/LogoRav.png
    
    #HUFFLEPUFF
    - images/Hufflepuff/hufflepuff1.png
    - images/Hufflepuff/hufflepuff.png
    - images/Hufflepuff/hufflepuff2.png
    - images/Hufflepuff/Huf1.png
    - images/Hufflepuff/Huf2.png
    - images/Hufflepuff/Huf3.png
    - images/Hufflepuff/LogoHuf.png

    #FONDO/IMAGENES LOGIN - PORTADA - REGISTRO
    - images/fondo_01.jpg
    - images/fondo_02.jpg
    - images/fondo_03.jpg
    - images/hat.png
    - images/carta.png
    - images/arrowdown.png

    #PELICULAS
    - images/Peliculas/1.jpg
    - images/Peliculas/2.jpg
    - images/Peliculas/3.jpg
    - images/Peliculas/4.jpg
    - images/Peliculas/5.jpg
    - images/Peliculas/6.jpg
    - images/Peliculas/7.jpg
    - images/Peliculas/8.jpg

    #LIBROS
    - images/Libros/1.jpg
    - images/Libros/2.jpg
    - images/Libros/3.jpg
    - images/Libros/4.jpg
    - images/Libros/5.jpg
    - images/Libros/6.jpg
    - images/Libros/7.jpg

    #IMAGENES RESPUSETAS TEST
    - images/RespuestasTest/pregunta1respuesta1.jpg
    - images/RespuestasTest/pregunta1respuesta2.jpeg
    - images/RespuestasTest/pregunta1respuesta3.jpeg
    - images/RespuestasTest/pregunta1respuesta4.jpeg

    - images/RespuestasTest/pregunta3respuesta1.jpeg
    - images/RespuestasTest/pregunta3respuesta2.jpeg
    - images/RespuestasTest/pregunta3respuesta3.jpeg
    - images/RespuestasTest/pregunta3respuesta4.jpg

    - images/RespuestasTest/pregunta5respuesta1.jpg
    - images/RespuestasTest/pregunta5respuesta2.jpg
    - images/RespuestasTest/pregunta5respuesta3.jpg
    - images/RespuestasTest/pregunta5respuesta4.jpg

    - images/RespuestasTest/pregunta7respuesta1.jpg
    - images/RespuestasTest/pregunta7respuesta2.jpg
    - images/RespuestasTest/pregunta7respuesta3.jpg
    - images/RespuestasTest/pregunta7respuesta4.jpg

    #IMAGENES TEST VARITA PATRONUS
    - images/TestVaritaPatronus/gryffindor.jpg
    - images/TestVaritaPatronus/slytherin.jpg
    - images/TestVaritaPatronus/ravenclaw.jpg
    - images/TestVaritaPatronus/hufflepuff.jpg
    
    #VARITAS
    - images/Varitas/varita1.png
    - images/Varitas/varita2.png
    - images/Varitas/varita3.png
    - images/Varitas/varita4.png
    - images/Varitas/varita5.png

    #PATRONUS
    - images/Patronus/Águila pescadora.png
    - images/Patronus/Ardilla Gris.png
    - images/Patronus/Búho marrón.png
    - images/Patronus/Busardo.png
    - images/Patronus/Gavilan.png
    - images/Patronus/Lobo Irlandes.png

    #TIENDA
    - images/Tienda/Jersey.png
    - images/Tienda/Bufanda.png
    - images/Tienda/Funko.png
    - images/Tienda/Jersey2.png
    - images/Tienda/Libro.png
    - images/Tienda/Niki.png
    - images/Tienda/Taza.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BluuNext
      fonts:
        - asset: fonts/BluuNext-Bold.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
